USE QLTC;
GO

CREATE LOGIN BOPHANDIEUHANH WITH PASSWORD = '12345';
CREATE LOGIN KHACHHANG WITH PASSWORD = '12345';
CREATE LOGIN NHANVIENYTE WITH PASSWORD = '12345';
CREATE LOGIN NHANVIENHUONGDAN WITH PASSWORD = '12345';
CREATE LOGIN NHANVIENKETOAN WITH PASSWORD = '12345';
CREATE LOGIN BACSI WITH PASSWORD = '12345';

------USER
CREATE USER BPDH FOR LOGIN BOPHANDIEUHANH;
CREATE USER KH FOR LOGIN KHACHHANG;
CREATE USER NVYT FOR LOGIN NHANVIENYTE;
CREATE USER NVHD FOR LOGIN NHANVIENHUONGDAN;
CREATE USER NVKT FOR LOGIN NHANVIENKETOAN;
CREATE USER BS FOR LOGIN BACSI;

------ ROLE
EXEC sp_addrole 'BOPHANDIEUHANH'
EXEC sp_addrole 'KHACHHANG'
EXEC sp_addrole 'NHANVIENYTE'
EXEC sp_addrole 'NHANVIENHUONGDAN'
EXEC sp_addrole 'NHANVIENKETOAN', 'dbo'
EXEC sp_addrole 'BACSI', 'dbo'

EXEC sp_addrolemember 'BOPHANDIEUHANH','BPDH'
EXEC sp_addrolemember 'KHACHHANG','KH'
EXEC sp_addrolemember 'NHANVIENYTE','NVYT'
EXEC sp_addrolemember 'NHANVIENHUONGDAN','NVHD'
EXEC sp_addrolemember 'NHANVIENKETOAN','NVKT'
EXEC sp_addrolemember 'BACSI','BS'

GO

------ PRIVILEGE
CREATE VIEW UV_THONGTINKH 
AS
	SELECT KH. *
	FROM KHACHHANG KH JOIN TAIKHOAN TK
	ON KH.MAKHACHHANG = TK.TENTAIKHOAN
	WHERE TK.TENTAIKHOAN = CURRENT_USER
	--CURRETUSER LÀ TÀI KHOẢN ĐANG ĐĂNG NHẬP 
GO

GRANT SELECT,UPDATE ON UV_THONGTINKH TO KH
GO

--- 2.Tạo view để BPDH chỉ được truy cập trên dữ liệu của mình
CREATE VIEW UV_THONGTINBPDH
AS
	SELECT BPDH. *
	FROM BOPHANDIEUHANH BPDH JOIN TAIKHOAN TK
	ON BPDH.MADIEUHANH = TK.TENTAIKHOAN
	WHERE TK.TENTAIKHOAN = CURRENT_USER
	--CURRETUSER LÀ TÀI KHOẢN ĐANG ĐĂNG NHẬP 
GO

GRANT SELECT ON UV_THONGTINBPDH TO BPDH
GO

--- 3.Tạo view để NVYT chỉ được truy cập trên dữ liệu của mình
CREATE VIEW UV_THONGTINNVYT
AS
	SELECT NV. *
	FROM NHANVIEN NV JOIN TAIKHOAN TK
	ON NV.MANHANVIEN = TK.TENTAIKHOAN AND NV.VITRI = 1
	WHERE TK.TENTAIKHOAN= CURRENT_USER 
	--CURRETUSER LÀ TÀI KHOẢN ĐANG ĐĂNG NHẬP 
GO

GRANT SELECT,UPDATE ON UV_THONGTINNVYT TO NVYT
GO

--- 4.Tạo view để NVKT chỉ được truy cập trên dữ liệu của mình
CREATE VIEW UV_THONGTINNVKT
AS
	SELECT NV. *
	FROM NHANVIEN NV JOIN TAIKHOAN TK
	ON NV.MANHANVIEN = TK.TENTAIKHOAN AND NV.VITRI = 3
	WHERE TK.TENTAIKHOAN= CURRENT_USER 
	--CURRETUSER LÀ TÀI KHOẢN ĐANG ĐĂNG NHẬP
GO

GRANT SELECT,UPDATE ON UV_THONGTINNVKT TO NVKT
GO

--- 5.Tạo view để NVHD chỉ được truy cập trên dữ liệu của mình
CREATE VIEW UV_THONGTINNVHD
AS
	SELECT NV. *
	FROM NHANVIEN NV JOIN TAIKHOAN TK
	ON NV.MANHANVIEN = TK.TENTAIKHOAN AND NV.VITRI = 0
	WHERE TK.TENTAIKHOAN= CURRENT_USER 
	--CURRETUSER LÀ TÀI KHOẢN ĐANG ĐĂNG NHẬP
GO

GRANT SELECT, UPDATE ON UV_THONGTINNVHD TO NVHD
GO

--- 6.Tạo view để BS chỉ được truy cập trên dữ liệu của mình
CREATE VIEW UV_THONGTINBS
AS
	SELECT NV. *
	FROM NHANVIEN NV JOIN TAIKHOAN TK
	ON NV.MANHANVIEN = TK.TENTAIKHOAN AND NV.VITRI = 2
	WHERE TK.TENTAIKHOAN= CURRENT_USER 
	--CURRETUSER LÀ TÀI KHOẢN ĐANG ĐĂNG NHẬP
GO

GRANT SELECT, UPDATE ON UV_THONGTINBS TO BS
GO